/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NewAnalysisRouteImport } from './routes/new-analysis'
import { Route as BlueprintIdRouteImport } from './routes/blueprint.$id'
import { Route as DiscoveryIdRouteImport } from './routes/discovery.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NewAnalysisRoute = NewAnalysisRouteImport.update({
  id: '/new-analysis',
  path: '/new-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintIdRoute = BlueprintIdRouteImport.update({
  id: '/blueprint/$id',
  path: '/blueprint/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryIdRoute = DiscoveryIdRouteImport.update({
  id: '/discovery/$id',
  path: '/discovery/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new-analysis': typeof NewAnalysisRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/discovery/$id': typeof DiscoveryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new-analysis': typeof NewAnalysisRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/discovery/$id': typeof DiscoveryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/new-analysis': typeof NewAnalysisRoute
  '/blueprint/$id': typeof BlueprintIdRoute
  '/discovery/$id': typeof DiscoveryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/dashboard' | '/new-analysis' | '/blueprint/$id' | '/discovery/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/new-analysis' | '/blueprint/$id' | '/discovery/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/new-analysis'
    | '/blueprint/$id'
    | '/discovery/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  NewAnalysisRoute: typeof NewAnalysisRoute
  BlueprintIdRoute: typeof BlueprintIdRoute
  DiscoveryIdRoute: typeof DiscoveryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-analysis': {
      id: '/new-analysis'
      path: '/new-analysis'
      fullPath: '/new-analysis'
      preLoaderRoute: typeof NewAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint/$id': {
      id: '/blueprint/$id'
      path: '/blueprint/$id'
      fullPath: '/blueprint/$id'
      preLoaderRoute: typeof BlueprintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery/$id': {
      id: '/discovery/$id'
      path: '/discovery/$id'
      fullPath: '/discovery/$id'
      preLoaderRoute: typeof DiscoveryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  NewAnalysisRoute: NewAnalysisRoute,
  BlueprintIdRoute: BlueprintIdRoute,
  DiscoveryIdRoute: DiscoveryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
